import { describe, expect, it } from 'vitest';
import { buildLsini4, buildLsini16, buildPsini, buildPtau, TWO_PI } from './tables.js';

describe('plasma tables', () => {
  it('psini has 16384 bytes generated by the verbatim formula', () => {
    const t = buildPsini();
    expect(t).toHaveLength(16384);
    // verbatim: trunc(sin(w)*55 + sin(6w)*5 + sin(21w)*4 + 64), stored as a byte
    for (const a of [0, 1, 1000, 4096, 12345, 16383]) {
      const w = (a * TWO_PI) / 4096;
      const expected =
        Math.trunc(Math.sin(w) * 55 + Math.sin(w * 6) * 5 + Math.sin(w * 21) * 4 + 64) & 255;
      expect(t[a]).toBe(expected);
    }
  });

  it('lsini4 / lsini16 have 8192 unsigned-16 words by their formulas', () => {
    const t4 = buildLsini4();
    const t16 = buildLsini16();
    expect(t4).toHaveLength(8192);
    expect(t16).toHaveLength(8192);
    for (const a of [0, 1, 2048, 4096, 8191]) {
      const w = (a * TWO_PI) / 4096;
      expect(t4[a]).toBe(
        Math.trunc((Math.sin(w) * 55 + Math.sin(w * 5) * 8 + Math.sin(w * 15) * 2 + 64) * 8) &
          0xffff,
      );
      expect(t16[a]).toBe(
        Math.trunc((Math.sin(w) * 55 + Math.sin(w * 4) * 5 + Math.sin(w * 17) * 3 + 64) * 16) &
          0xffff,
      );
    }
  });

  it('ptau is a 0..63 cosine ramp with ptau[0] forced to 0', () => {
    const t = buildPtau();
    expect(t).toHaveLength(256);
    expect(t[0]).toBe(0);
    expect(t[64]).toBe(63); // cos(2π)*31+32
    for (let a = 0; a <= 64; a++) {
      expect(t[a]).toBeGreaterThanOrEqual(0);
      expect(t[a]).toBeLessThanOrEqual(63);
    }
  });
});
